"""all tables have been renamed from singular to plural

Revision ID: 7e176e138fc3
Revises: 1284289bf083
Create Date: 2023-10-15 17:49:42.922302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e176e138fc3"
down_revision = "1284289bf083"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.rename_table('exercise_type', 'dict_exercises', schema='datasets')
    op.rename_table('exercises_set_type', 'dict_supersets', schema='datasets')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
