"""Test ORM changes

Revision ID: e657aa2246c7
Revises: 90581cf80d33
Create Date: 2023-05-17 01:04:53.504554

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e657aa2246c7'
down_revision = '90581cf80d33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'id',
                    existing_type=sa.UUID(),
                    comment='Идентификатор',
                    existing_comment='идентификатор упражнения',
                    existing_nullable=False,
                    schema='workout')
    op.alter_column('exercise', 'comment',
                    existing_type=sa.TEXT(),
                    comment='Комментарий',
                    existing_comment='комментарий к упражнению',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('exercise_result', 'comment',
                    existing_type=sa.TEXT(),
                    comment='Комментарий',
                    existing_comment='комментарий к результату упражнения',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('exercises_set', 'id',
                    existing_type=sa.UUID(),
                    comment='Идентификатор',
                    existing_comment='идентификатор комплекса',
                    existing_nullable=False,
                    schema='workout')
    op.alter_column('exercises_set', 'comment',
                    existing_type=sa.TEXT(),
                    comment='Комментарий',
                    existing_comment='комментарий к комплексу',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('set_result', 'comment',
                    existing_type=sa.TEXT(),
                    comment='Комментарий',
                    existing_comment='комментарий к результату комплекса',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('workout_of_day', 'id',
                    existing_type=sa.UUID(),
                    comment='Идентификатор',
                    existing_comment='идентификатор тренировки',
                    existing_nullable=False,
                    schema='workout')
    op.alter_column('workout_of_day', 'comment',
                    existing_type=sa.TEXT(),
                    comment='Комментарий',
                    existing_comment='комментарий к тренировке',
                    existing_nullable=True,
                    schema='workout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_of_day', 'comment',
                    existing_type=sa.TEXT(),
                    comment='комментарий к тренировке',
                    existing_comment='Комментарий',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('workout_of_day', 'id',
                    existing_type=sa.UUID(),
                    comment='идентификатор тренировки',
                    existing_comment='Идентификатор',
                    existing_nullable=False,
                    schema='workout')
    op.alter_column('set_result', 'comment',
                    existing_type=sa.TEXT(),
                    comment='комментарий к результату комплекса',
                    existing_comment='Комментарий',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('exercises_set', 'comment',
                    existing_type=sa.TEXT(),
                    comment='комментарий к комплексу',
                    existing_comment='Комментарий',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('exercises_set', 'id',
                    existing_type=sa.UUID(),
                    comment='идентификатор комплекса',
                    existing_comment='Идентификатор',
                    existing_nullable=False,
                    schema='workout')
    op.alter_column('exercise_result', 'comment',
                    existing_type=sa.TEXT(),
                    comment='комментарий к результату упражнения',
                    existing_comment='Комментарий',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('exercise', 'comment',
                    existing_type=sa.TEXT(),
                    comment='комментарий к упражнению',
                    existing_comment='Комментарий',
                    existing_nullable=True,
                    schema='workout')
    op.alter_column('exercise', 'id',
                    existing_type=sa.UUID(),
                    comment='идентификатор упражнения',
                    existing_comment='Идентификатор',
                    existing_nullable=False,
                    schema='workout')
    # ### end Alembic commands ###
